"""
modules/acl_generator.py

Dynamic Cisco ACL Generator — Threat Intelligence Engine

Reads threat_scores.csv (output of threat_score.py) and generates a
deterministic, explainable Cisco IOS extended ACL configuration file.

Policy (frozen for dissertation prototype):
    Critical -> deny ip host <IP> any log            (full block)
    High     -> deny tcp host <IP> any eq 22 log      (SSH-only block)
    Medium   -> permit tcp host <IP> any eq 22 log    (allow + log, observation only)
    Low      -> no ACL entry generated

Design notes (read before citing this module in your implementation chapter):
    - This implements per-IP ACL enforcement only (Critical/High), with a
      logging-only Medium tier. The full four-tier response architecture
      (per-IP ACL / CIDR ACL / CoPP / RTBH) from the methodology chapter is
      NOT implemented here — CIDR aggregation, CoPP, and RTBH should be
      described as future work, not silently omitted from the write-up.
    - Medium-risk IPs use `permit ... log`, not a bare `remark`. A remark
      is a comment only — it has no effect on traffic handling or logging.
      `permit ... log` actually produces observable syslog evidence.
    - Output opens with `no ip access-list extended <name>` so repeated
      pushes via Netmiko REPLACE the ACL instead of appending duplicate
      entries on top of a previous version.
    - IPv4 only. Non-IPv4 entries are written to a `.skipped.txt` file
      alongside the output rather than silently dropped or crashing.
"""

import argparse
import ipaddress
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd

# ============================================================
# CONFIG — adjust COLUMN_MAP to match your actual threat_scores.csv headers
# ============================================================

COLUMN_MAP = {
    "ip": "src_ip",
    "risk": "risk_level",
    "score": "threat_score"
}


ACL_NAME = "DYNAMIC-SSH-DEFENSE"
SSH_PORT = 22

RISK_ORDER = ["Critical", "High", "Medium", "Low"]


def load_threat_scores(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"threat_scores.csv not found at: {path}")

    df = pd.read_csv(path)

    ip_col, risk_col = COLUMN_MAP["ip"], COLUMN_MAP["risk"]
    missing = [c for c in (ip_col, risk_col) if c not in df.columns]
    if missing:
        raise ValueError(
            f"threat_scores.csv is missing expected column(s): {missing}. "
            f"Found columns: {list(df.columns)}. "
            f"Update COLUMN_MAP at the top of acl_generator.py to match your schema."
        )
    return df


def split_valid_ipv4(df: pd.DataFrame, ip_col: str):
    """Return (valid_rows_df, skipped_ip_list). Skipped = non-IPv4 or malformed."""
    valid_mask = []
    skipped = []
    for ip in df[ip_col]:
        try:
            ipaddress.IPv4Address(str(ip).strip())
            valid_mask.append(True)
        except ValueError:
            valid_mask.append(False)
            skipped.append(str(ip))
    return df[pd.Series(valid_mask, index=df.index)], skipped


def build_acl_lines(df: pd.DataFrame) -> list:
    ip_col, risk_col = COLUMN_MAP["ip"], COLUMN_MAP["risk"]

    lines = [
        "!",
        "! =====================================================",
        "! Dynamic Cisco ACL",
        "! Generated by Threat Intelligence Engine",
        "! Research Prototype",
        f"! Generated: {datetime.now(timezone.utc).isoformat()}",
        "! =====================================================",
        "!",
        f"no ip access-list extended {ACL_NAME}",
        f"ip access-list extended {ACL_NAME}",
    ]

    grouped = {r: df[df[risk_col] == r] for r in RISK_ORDER}

    if not grouped["Critical"].empty:
        lines.append(" remark ===== Critical Threats =====")
        for ip in grouped["Critical"][ip_col]:
            lines.append(f" deny ip host {ip} any log")

    if not grouped["High"].empty:
        lines.append(" remark ===== High Threats =====")
        for ip in grouped["High"][ip_col]:
            lines.append(f" deny tcp host {ip} any eq {SSH_PORT} log")

    if not grouped["Medium"].empty:
        lines.append(" remark ===== Medium Threats (observation only) =====")
        for ip in grouped["Medium"][ip_col]:
            lines.append(f" permit tcp host {ip} any eq {SSH_PORT} log")

    # Low: intentionally no ACL entries generated (per frozen policy)

    lines.append(" permit ip any any")
    lines.append("")
    lines.append("end")
    lines.append("!")
    return lines


def generate_acl(threat_scores_path, output_path, skipped_log_path=None):
    """
    Read threat_scores.csv, write a Cisco IOS extended ACL config file.

    Returns the output Path. Raises FileNotFoundError / ValueError on
    missing input or schema mismatch — these are meant to surface loudly
    rather than fail silently, since a broken run should not produce a
    half-empty ACL file that looks valid.
    """
    threat_scores_path = Path(threat_scores_path)
    output_path = Path(output_path)

    df = load_threat_scores(threat_scores_path)
    ip_col = COLUMN_MAP["ip"]

    valid_df, skipped = split_valid_ipv4(df, ip_col)

    lines = build_acl_lines(valid_df)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    if skipped:
        skipped_log_path = Path(skipped_log_path) if skipped_log_path else output_path.with_suffix(".skipped.txt")
        skipped_log_path.write_text(
            "Entries skipped (not valid IPv4 — unsupported by this ACL type):\n"
            + "\n".join(skipped) + "\n"
        )
        print(f"[warn] {len(skipped)} non-IPv4 entr{'y' if len(skipped) == 1 else 'ies'} skipped -> {skipped_log_path}")

    counts = valid_df[COLUMN_MAP["risk"]].value_counts().reindex(RISK_ORDER, fill_value=0)
    print(f"[ok] wrote {output_path}")
    for r in RISK_ORDER:
        print(f"  {r:9s}: {counts[r]}")

    return output_path


def main():
    parser = argparse.ArgumentParser(description="Generate dynamic Cisco ACL from threat_scores.csv")
    parser.add_argument("--input", required=True, type=Path, help="Path to threat_scores.csv")
    parser.add_argument("--output", required=True, type=Path, help="Path to write generated_acl.cfg")
    args = parser.parse_args()
    generate_acl(args.input, args.output)


if __name__ == "__main__":
    main()
